spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri:
            scope:
              - profile
              - email
          kakao:
            client-name:
            client-id:
            authorization-grant-type:
            redirect-uri:
        provider:
          google:
            authorization-uri:
            token-uri:
            user-info-uri:
          kakao:
            user-name-attribute:
            authorization-uri:
            token-uri:
            user-info-uri:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      # schema.sql, data.sql 사용
      mode: always

logging:
  level:
    root: WARN
    org.springframework: INFO
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
